"""
Export generated playlists to Spotify via the spotipy library.

Requires:
  - pip install spotipy
  - SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET env vars or config
  - User authorization via OAuth (browser redirect flow)

Usage:
    from playlistgen.spotify_export import export_playlist_to_spotify
    url = export_playlist_to_spotify(playlist_df, "My Playlist", cfg=cfg)
"""

import logging
import os
from typing import Optional

import pandas as pd

try:
    import spotipy
    from spotipy.oauth2 import SpotifyOAuth

    SPOTIPY_AVAILABLE = True
except ImportError:
    SPOTIPY_AVAILABLE = False


def _get_user_spotify(
    client_id: Optional[str] = None,
    client_secret: Optional[str] = None,
    redirect_uri: Optional[str] = None,
) -> Optional["spotipy.Spotify"]:
    """Return an authenticated spotipy client with user-level scopes."""
    if not SPOTIPY_AVAILABLE:
        logging.error(
            "spotipy not installed. Install with: pip install 'playlistgen[spotify]'"
        )
        return None

    cid = client_id or os.getenv("SPOTIFY_CLIENT_ID")
    secret = client_secret or os.getenv("SPOTIFY_CLIENT_SECRET")
    redir = redirect_uri or os.getenv("SPOTIFY_REDIRECT_URI", "http://localhost:8888/callback")

    if not cid or not secret:
        logging.error(
            "Spotify export requires SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET. "
            "Set them as environment variables or in config.yml."
        )
        return None

    scope = "playlist-modify-public playlist-modify-private"
    auth_manager = SpotifyOAuth(
        client_id=cid,
        client_secret=secret,
        redirect_uri=redir,
        scope=scope,
    )
    return spotipy.Spotify(auth_manager=auth_manager)


def _search_track(sp: "spotipy.Spotify", artist: str, name: str) -> Optional[str]:
    """Search Spotify for a track and return its URI, or None if not found."""
    query = f"artist:{artist} track:{name}"
    try:
        results = sp.search(q=query, type="track", limit=1)
        items = results.get("tracks", {}).get("items", [])
        if items:
            return items[0]["uri"]
    except Exception as exc:
        logging.debug("Spotify search failed for '%s - %s': %s", artist, name, exc)
    return None


def export_playlist_to_spotify(
    df: pd.DataFrame,
    playlist_name: str,
    cfg: Optional[dict] = None,
    public: bool = True,
    description: str = "",
) -> Optional[str]:
    """
    Export a playlist DataFrame to the user's Spotify account.

    Searches Spotify for each track by artist + name and creates a new playlist
    with the matched tracks. Tracks not found on Spotify are skipped.

    Args:
        df:             Playlist DataFrame with 'Artist' and 'Name' columns.
        playlist_name:  Name for the Spotify playlist.
        cfg:            Optional config dict (for credentials and redirect URI).
        public:         Whether the playlist should be public (default True).
        description:    Optional playlist description.

    Returns:
        The Spotify playlist URL if successful, None otherwise.
    """
    if cfg is None:
        from .config import load_config
        cfg = load_config()

    sp = _get_user_spotify(
        client_id=cfg.get("SPOTIFY_CLIENT_ID"),
        client_secret=cfg.get("SPOTIFY_CLIENT_SECRET"),
        redirect_uri=cfg.get("SPOTIFY_REDIRECT_URI"),
    )
    if sp is None:
        return None

    # Get current user ID
    try:
        user = sp.current_user()
        user_id = user["id"]
    except Exception as exc:
        logging.error("Failed to get Spotify user info: %s", exc)
        return None

    # Search for tracks
    track_uris = []
    not_found = []
    for _, row in df.iterrows():
        artist = str(row.get("Artist", "")).strip()
        name = str(row.get("Name", "")).strip()
        if not artist or not name:
            continue
        uri = _search_track(sp, artist, name)
        if uri:
            track_uris.append(uri)
        else:
            not_found.append(f"{artist} - {name}")

    if not track_uris:
        logging.error("No tracks found on Spotify — cannot create playlist.")
        return None

    logging.info(
        "Spotify export: found %d/%d tracks. %d not found.",
        len(track_uris),
        len(track_uris) + len(not_found),
        len(not_found),
    )
    if not_found and len(not_found) <= 10:
        for nf in not_found:
            logging.info("  Not found: %s", nf)

    # Create playlist
    if not description:
        description = f"Generated by PlaylistGen ({len(track_uris)} tracks)"

    try:
        playlist = sp.user_playlist_create(
            user=user_id,
            name=playlist_name,
            public=public,
            description=description,
        )
        playlist_id = playlist["id"]
    except Exception as exc:
        logging.error("Failed to create Spotify playlist: %s", exc)
        return None

    # Add tracks in batches of 100 (Spotify API limit)
    for i in range(0, len(track_uris), 100):
        batch = track_uris[i : i + 100]
        try:
            sp.playlist_add_items(playlist_id, batch)
        except Exception as exc:
            logging.error("Failed to add tracks to playlist: %s", exc)

    url = playlist.get("external_urls", {}).get("spotify", "")
    logging.info("Spotify playlist created: '%s' → %s", playlist_name, url)
    return url
